- name: My first play
  hosts: myhosts
  tasks:
   - name: Ping my hosts
     ansible.builtin.ping:

   - name: Print message
     ansible.builtin.debug:
      msg: Hello world
   
   - name: Install Java
     apt:
      name: temurin-11-jdk
      update-cache: yes
      state: present